"""Generate the offline WebUI from production assets; never import user configuration."""

from __future__ import annotations

import argparse
import ast
import base64
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def literals(path: Path) -> dict:
    values = {}
    for node in ast.parse(path.read_text(encoding="utf-8")).body:
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            values[node.target.id] = ast.literal_eval(node.value)
        elif isinstance(node, ast.Assign) and isinstance(node.targets[0], ast.Name):
            try:
                values[node.targets[0].id] = ast.literal_eval(node.value)
            except (ValueError, TypeError):
                continue
    return values


def demo_schema(root: Path) -> dict:
    metadata = literals(root / "src/webui/config_editor.py")
    examples = literals(root / "config.example.py")
    groups = {}
    for group, fields in metadata["FIELD_SPECS"].items():
        current = examples.get(metadata["GROUP_SOURCES"][group], {})
        entries = {}
        for field, spec in fields.items():
            if spec.get("tier") == "hidden" or spec.get("editor") == "persona":
                continue
            entry = dict(spec)
            value = current
            for part in field.split("."):
                value = value.get(part) if isinstance(value, dict) else None
            entry["value"] = spec.get("default") if value is None else value
            if spec.get("sensitive"):
                entry.update(value=None, is_set=field == "token" or bool(value))
            entries[field] = entry
        groups[group] = {
            **metadata["GROUP_META"].get(group, {}),
            "source": metadata["GROUP_SOURCES"][group], "fields": entries,
        }
    groups["voice"]["fields"]["enabled"]["value"] = True
    groups["voice"]["fields"]["backend"]["value"] = "mimo_cascade"
    return groups


def build(root: Path = ROOT) -> str:
    assets = root / "src/webui/assets"
    html = (assets / "index.html").read_text(encoding="utf-8")
    fixture = {
        "groups": demo_schema(root),
        "auto_visit": literals(root / "config.example.py")["VOICE_AUTO_VISIT_CONFIG"],
        "version": literals(root / "src/core/version.py")["RELEASE_BASE_VERSION"],
    }
    payload = json.dumps(fixture, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
    mock = (root / "scripts/webui_preview.js").read_text(encoding="utf-8")
    html = html.replace("<title>Ooptra", "<title>离线预览 · Ooptra")
    html = html.replace("<body>", '<body>\n<aside class="preview-banner" role="note">'
                        '离线交互预览 · 演示密码：<b>demo</b> · 操作仅影响本页演示数据'
                        '</aside>\n<style>.preview-banner{position:sticky;top:0;z-index:1000;'
                        'padding:8px 16px;text-align:center;background:#263b61;color:#fff;'
                        'font:13px/1.6 system-ui}.preview-banner b{color:#fff}</style>'
                        '\n<script>window.OOPTRA_PREVIEW=' + payload + ';</script>\n'
                        '<script>\n' + mock.replace("</script", "<\\/script") + '\n</script>')

    def script(match):
        source = (assets / match[1]).read_text(encoding="utf-8")
        # Preview preferences must not alter a running console on the same origin.
        source = source.replace("oopz.webui.", "ooptra.preview.")
        return '<script>\n' + source.replace("</script", "<\\/script") + '\n</script>'

    html = re.sub(r'<script src="/assets/([^"/]+)"></script>', script, html)
    html = re.sub(r'<link rel="stylesheet" href="/assets/style.css"\s*/?>',
                  lambda _: '<style>\n' + (assets / "style.css").read_text(encoding="utf-8") + '\n</style>', html)
    for name in ("logo.svg", "favicon.svg"):
        svg = (assets / name).read_text(encoding="utf-8").encode("utf-8")
        data = base64.b64encode(svg).decode("ascii")
        html = html.replace("/assets/" + name, "data:image/svg+xml;base64," + data)
    if 'src="/assets/' in html or 'href="/assets/' in html:
        raise ValueError("New WebUI assets need an inline preview rule")
    return '<!-- Generated by python scripts/build_webui_preview.py; edit source assets instead. -->\n' + html


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if committed preview is stale")
    args = parser.parse_args()
    expected = build()
    output = ROOT / "webui_preview.html"
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != expected:
            print("webui_preview.html is stale. Run: python scripts/build_webui_preview.py")
            return 1
        print("Standalone WebUI preview matches current sources.")
    else:
        output.write_text(expected, encoding="utf-8", newline="\n")
        print("Generated webui_preview.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
